### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by MqtUA** [JamesAltemus/SWTOR-Guild-Roster#1]
Got an error when tried this script. I am not a Python programmer so can't solve this myself, and googling didn't help.
Running game on laptop. To run script using Python 3.8 
```
λ python SWTOR-Guild-Roster-CQ-Points.py
This program will scroll through the guild roster and gather the CQ point information.

This program requires tesseract. Please ensure tesseract is installed before continuing.
Tesseract can be downloaded from: https://github.com/tesseract-ocr/tesseract/blob/master/README.md
For Windows, Tesseract can be downloaded from: https://github.com/UB-Mannheim/tesseract/wiki

If tesseract is installed in C:/Program Files/Tesseract-OCR/tesseract press any key to continue
otherwise please enter the installation location now.
C:/Program Files/Tesseract-OCR/
Please enter the guild name.
test
Please enter the number of members in the guild.
6
Before you continue be sure SWTOR is set up as followed:
  * The guild window must be open
  * Show offline members should be selected
  * The last column should be set to CQ points
  * The second to last column should be set to rank
  * Ensure the guild window is completely visable and unobstructed by anything including this program. resize if needed

If the following are done, press any key to continue...

Now processing the guild roster. Do not touch the mouse, keyboard, or computer...

|
                | 0.00%Traceback (most recent call last):
  File "conquest.py", line 377, in <module>
    gather_cq_points()
  File "conquest.py", line 295, in gather_cq_points
    roster_area = id_roster()
  File "conquest.py", line 36, in id_roster
    return (top[0], top[1], bot[0]+bot[2]-top[0], bot[1]+bot[3]-top[1])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by JamesAltemus** [comment]
It couldn't find a match for CornerTop.png or CornerBot.png.

Try taking screenshots similar to the images I provided and run it again. Let me know if you still get the error.

**Comment by MqtUA** [comment]
I replaced all pictures and it solved one problem, I've seen mouse moved to scroll bar, but another error occurred:
```
λ python conquest.py
This program will scroll through the guild roster and gather the CQ point information.

This program requires tesseract. Please ensure tesseract is installed before continuing.
Tesseract can be downloaded from: https://github.com/tesseract-ocr/tesseract/blob/master/README.md
For Windows, Tesseract can be downloaded from: https://github.com/UB-Mannheim/tesseract/wiki

If tesseract is installed in C:/Program Files/Tesseract-OCR/tesseract press any key to continue
otherwise please enter the installation location now.

Please enter the guild name.
test
Please enter the number of members in the guild.
10
Before you continue be sure SWTOR is set up as followed:
  * The guild window must be open
  * Show offline members should be selected
  * The last column should be set to CQ points
  * The second to last column should be set to rank
  * Ensure the guild window is completely visable and unobstructed by anything including this program. resize if needed

If the following are done, press any key to continue...

Now processing the guild roster. Do not touch the mouse, keyboard, or computer...

|
                | 0.00%Traceback (most recent call last):
  File "C:\Users\maxpu\AppData\Roaming\Python\Python38\site-packages\PIL\ImageFile.py", line 506, in _save
    fh = fp.fileno()
AttributeError: '_idat' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "conquest.py", line 376, in <module>
    gather_cq_points()
  File "conquest.py", line 310, in gather_cq_points
    roster, ierr, nerr = pic_to_text(roster, tess_install)
  File "conquest.py", line 146, in pic_to_text
    char.append(pytesseract.image_to_string(image, lang='eng'))
  File "C:\Users\maxpu\AppData\Roaming\Python\Python38\site-packages\pytesseract\pytesseract.py", line 370, in image_to_string
    return {
  File "C:\Users\maxpu\AppData\Roaming\Python\Python38\site-packages\pytesseract\pytesseract.py", line 373, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "C:\Users\maxpu\AppData\Roaming\Python\Python38\site-packages\pytesseract\pytesseract.py", line 271, in run_and_get_output
    with save(image) as (temp_name, input_filename):
  File "C:\Program Files\Python38\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "C:\Users\maxpu\AppData\Roaming\Python\Python38\site-packages\pytesseract\pytesseract.py", line 196, in save
    image.save(input_file_name, format=image.format)
  File "C:\Users\maxpu\AppData\Roaming\Python\Python38\site-packages\PIL\Image.py", line 2158, in save
    save_handler(self, fp, filename)
  File "C:\Users\maxpu\AppData\Roaming\Python\Python38\site-packages\PIL\PngImagePlugin.py", line 1284, in _save
    ImageFile._save(im, _idat(fp, chunk), [("zip", (0, 0) + im.size, 0, rawmode)])
  File "C:\Users\maxpu\AppData\Roaming\Python\Python38\site-packages\PIL\ImageFile.py", line 514, in _save
    e.setimage(im.im, b)
SystemError: tile cannot extend outside image
```

**Comment by MqtUA** [comment]
Attaching new images for screen resolution 1366*768. 
![CornerBot](https://user-images.githubusercontent.com/26764029/96022529-abac3500-0e59-11eb-9dfd-f0e1133376b4.png)
![CornerTop](https://user-images.githubusercontent.com/26764029/96022533-ac44cb80-0e59-11eb-8709-f36c1091e494.png)
![Scroll_Bar](https://user-images.githubusercontent.com/26764029/96022536-ad75f880-0e59-11eb-9deb-e6dab9087a50.png)

**Comment by JamesAltemus** [comment]
Hmm. What version of pytesseract are you running? I created this using version 0.3.3.

**Comment by MqtUA** [comment]
Version 0.3.6 from pip.

**Comment by MqtUA** [comment]
Tried with version 0.3.3, same result.
